import palettes from '../palette';
export const bgFill = {
  defaultPrimary: palettes.white,
  /**
   * @deprecated May remove later
   */
  defaultPrimaryII: palettes.white,
  defaultSecondary: palettes.grey50,
  defaultTertiary: palettes.grey100,
  defaultDisabled: palettes.grey50,
  defaultInverse: palettes.grey900,
  brand: palettes.orange500,
  brandSecondary: palettes.orange50,
  brandTertiary: palettes.orange0,
  brandHover: palettes.orange600,
  brandSecondaryHover: palettes.orange100,
  accent: palettes.blue700,
  accentSecondary: palettes.blue50,
  /**
   * @deprecated May remove later
   */
  accentSecondaryII: palettes.blue50,
  accentTertiary: palettes.skyBlue0,
  accentHover: palettes.blue800,
  accentSecondaryHover: palettes.blue100,
  stateError: palettes.red500,
  stateErrorSecondary: palettes.red50,
  stateErrorHover: palettes.red700,
  stateErrorSecondaryHover: palettes.red100,
  stateWarning: palettes.yellow500,
  stateWarningSecondary: palettes.yellow50,
  stateSuccess: palettes.green500,
  stateSuccessSecondary: palettes.green50,
  miscMagenta: palettes.magenta600,
  miscMagentaSecondary: palettes.magenta50,
  miscTeal: palettes.teal600,
  miscTealSecondary: palettes.teal50,
  miscPurple: palettes.purple600,
  miscPurpleSecondary: palettes.purple50,
  miscCrimson: palettes.crimson600,
  miscCrimsonSecondary: palettes.crimson50,
  translucentPrimary: palettes.whiteAlpha100,
  translucentSecondary: palettes.whiteAlpha400,
  translucentTertiary: palettes.whiteAlpha700,
  miscGold: palettes.gold400,
  miscGoldSecondary: palettes.gold50,
  miscGoldTertiary: palettes.gold0,
  miscGoldHover: palettes.gold600,
  miscGoldSecondaryHover: palettes.gold800
};
export const bgSurface = {
  defaultPrimary: palettes.white,
  defaultSecondary: palettes.grey50,
  defaultDisabled: palettes.grey50,
  defaultInverse: palettes.grey900,
  brand: palettes.orange50,
  accent: palettes.blue50,
  stateError: palettes.red50,
  stateWarning: palettes.yellow50,
  stateSuccess: palettes.green50,
  miscMagenta: palettes.magenta50,
  miscTeal: palettes.teal50,
  miscPurple: palettes.purple50,
  miscCrimson: palettes.crimson50,
  overlayPrimary: palettes.grey700,
  miscGold: palettes.gold0
};
export const text = {
  defaultPrimary: palettes.grey900,
  defaultSecondary: palettes.grey500,
  defaultTertiary: palettes.grey300,
  defaultDisabled: palettes.grey300,
  defaultInverse: palettes.white,
  brand: palettes.orange500,
  brandInverse: palettes.white,
  brandHover: palettes.orange600,
  brandAccent: palettes.blue700,
  brandAccentInverse: palettes.white,
  stateWarning: palettes.yellow600,
  stateWarningInverse: palettes.white,
  stateError: palettes.red500,
  stateErrorInverse: palettes.white,
  stateSuccess: palettes.green500,
  stateSuccessInverse: palettes.white,
  miscMagenta: palettes.magenta600,
  miscMagentaInverse: palettes.white,
  miscTeal: palettes.teal600,
  miscTealInverse: palettes.white,
  miscPurple: palettes.purple600,
  miscPurpleInverse: palettes.white,
  miscCrimson: palettes.crimson600,
  miscCrimsonInverse: palettes.white,
  miscGold: palettes.gold600,
  miscGoldInverse: palettes.white
};
export const border = {
  defaultPrimary: palettes.grey200,
  defaultSecondary: palettes.grey300,
  defaultBrand: palettes.orange500,
  defaultAccent: palettes.blue700,
  defaultDisabled: palettes.grey200,
  defaultWhite: palettes.white,
  defaultInverse: palettes.grey900,
  stateError: palettes.red300,
  stateWarning: palettes.yellow300,
  stateSuccess: palettes.green300,
  miscMagenta: palettes.magenta400,
  miscTeal: palettes.teal400,
  miscPurple: palettes.purple400,
  miscCrimson: palettes.crimson400,
  miscGold: palettes.gold400
};
export const icon = {
  defaultPrimary: palettes.grey900,
  defaultSecondary: palettes.grey500,
  defaultTertiary: palettes.grey300,
  defaultDisabled: palettes.grey300,
  defaultInverse: palettes.white,
  brand: palettes.orange500,
  brandInverse: palettes.white,
  brandHover: palettes.orange600,
  accent: palettes.blue700,
  accentInverse: palettes.white,
  warning: palettes.yellow500,
  warningInverse: palettes.white,
  error: palettes.red500,
  errorInverse: palettes.white,
  success: palettes.green500,
  successInverse: palettes.white,
  magenta: palettes.magenta600,
  magentaInverse: palettes.white,
  teal: palettes.teal600,
  tealInverse: palettes.white,
  purple: palettes.purple600,
  purpleInverse: palettes.white,
  crimson: palettes.crimson600,
  crimsonInverse: palettes.white,
  miscGold: palettes.gold500,
  miscGoldInverse: palettes.white
};
const BaseColors = {
  bgFill,
  icon,
  border,
  text,
  bgSurface
};
export default BaseColors;
//# sourceMappingURL=index.js.map