declare const orbitColor: {
    bgFill: {
        /**
         * @deprecated May remove later
         */
        defaultPrimaryII: string;
        brand: string;
        brandSecondary: string;
        brandSecondaryHover: string;
        brandHover: string;
        defaultPrimary: string;
        defaultSecondary: string;
        defaultTertiary: string;
        defaultDisabled: string;
        defaultInverse: string;
        accent: string;
        accentHover: string;
        stateWarning: string;
        stateWarningSecondary: string;
        stateSuccess: string;
        /**
         * @deprecated May remove later
         */
        accentSecondaryII: string;
        brandTertiary: string;
        accentSecondary: string;
        accentTertiary: string;
        accentSecondaryHover: string;
        stateError: string;
        stateErrorSecondary: string;
        stateErrorHover: string;
        stateErrorSecondaryHover: string;
        stateSuccessSecondary: string;
        miscMagenta: string;
        miscMagentaSecondary: string;
        miscTeal: string;
        miscTealSecondary: string;
        miscPurple: string;
        miscPurpleSecondary: string;
        miscCrimson: string;
        miscCrimsonSecondary: string;
        translucentPrimary: string;
        translucentSecondary: string;
        translucentTertiary: string;
        miscGold: string;
        miscGoldSecondary: string;
        miscGoldTertiary: string;
        miscGoldHover: string;
        miscGoldSecondaryHover: string;
    };
    bgSurface: {
        defaultInverse: string;
        brand: string;
        accent: string;
        stateWarning: string;
        overlayPrimary: string;
        defaultPrimary: string;
        defaultSecondary: string;
        defaultDisabled: string;
        stateError: string;
        stateSuccess: string;
        miscMagenta: string;
        miscTeal: string;
        miscPurple: string;
        miscCrimson: string;
        miscGold: string;
    };
    text: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        brandInverse: string;
        brandHover: string;
        brandAccent: string;
        stateWarning: string;
        stateError: string;
        stateSuccess: string;
        defaultTertiary: string;
        brandAccentInverse: string;
        stateWarningInverse: string;
        stateErrorInverse: string;
        stateSuccessInverse: string;
        miscMagenta: string;
        miscMagentaInverse: string;
        miscTeal: string;
        miscTealInverse: string;
        miscPurple: string;
        miscPurpleInverse: string;
        miscCrimson: string;
        miscCrimsonInverse: string;
        miscGold: string;
        miscGoldInverse: string;
    };
    border: {
        defaultPrimary: string;
        defaultBrand: string;
        defaultAccent: string;
        defaultDisabled: string;
        stateWarning: string;
        stateSuccess: string;
        defaultSecondary: string;
        defaultWhite: string;
        defaultInverse: string;
        stateError: string;
        miscMagenta: string;
        miscTeal: string;
        miscPurple: string;
        miscCrimson: string;
        miscGold: string;
    };
    icon: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        brandInverse: string;
        brandHover: string;
        accent: string;
        accentInverse: string;
        warning: string;
        success: string;
        defaultTertiary: string;
        warningInverse: string;
        error: string;
        errorInverse: string;
        successInverse: string;
        magenta: string;
        magentaInverse: string;
        teal: string;
        tealInverse: string;
        purple: string;
        purpleInverse: string;
        crimson: string;
        crimsonInverse: string;
        miscGold: string;
        miscGoldInverse: string;
    };
};
export default orbitColor;
//# sourceMappingURL=index.d.ts.map