export let STATE_TYPES = /*#__PURE__*/function (STATE_TYPES) {
  STATE_TYPES["DEFAULT"] = "DEFAULT";
  STATE_TYPES["PRESSED"] = "PRESSED";
  STATE_TYPES["UPLOADING"] = "UPLOADING";
  STATE_TYPES["UPLOAD_COMPLETE"] = "UPLOAD_COMPLETE";
  STATE_TYPES["UPLOAD_FAILED"] = "UPLOAD_FAILED";
  STATE_TYPES["ERROR"] = "ERROR";
  STATE_TYPES["DISABLED"] = "DISABLED";
  STATE_TYPES["CUSTOM"] = "CUSTOM";
  return STATE_TYPES;
}({});
//# sourceMappingURL=types.js.map