export declare const bgFill: {
    defaultPrimary: string;
    /**
     * @deprecated May remove later
     */
    defaultPrimaryII: string;
    defaultSecondary: string;
    defaultTertiary: string;
    defaultDisabled: string;
    defaultInverse: string;
    brand: string;
    brandSecondary: string;
    brandTertiary: string;
    brandHover: string;
    brandSecondaryHover: string;
    accent: string;
    accentSecondary: string;
    /**
     * @deprecated May remove later
     */
    accentSecondaryII: string;
    accentTertiary: string;
    accentHover: string;
    accentSecondaryHover: string;
    stateError: string;
    stateErrorSecondary: string;
    stateErrorHover: string;
    stateErrorSecondaryHover: string;
    stateWarning: string;
    stateWarningSecondary: string;
    stateSuccess: string;
    stateSuccessSecondary: string;
    miscMagenta: string;
    miscMagentaSecondary: string;
    miscTeal: string;
    miscTealSecondary: string;
    miscPurple: string;
    miscPurpleSecondary: string;
    miscCrimson: string;
    miscCrimsonSecondary: string;
    translucentPrimary: string;
    translucentSecondary: string;
    translucentTertiary: string;
    miscGold: string;
    miscGoldSecondary: string;
    miscGoldTertiary: string;
    miscGoldHover: string;
    miscGoldSecondaryHover: string;
};
export declare const bgSurface: {
    defaultPrimary: string;
    defaultSecondary: string;
    defaultDisabled: string;
    defaultInverse: string;
    brand: string;
    accent: string;
    stateError: string;
    stateWarning: string;
    stateSuccess: string;
    miscMagenta: string;
    miscTeal: string;
    miscPurple: string;
    miscCrimson: string;
    overlayPrimary: string;
    miscGold: string;
};
export declare const text: {
    defaultPrimary: string;
    defaultSecondary: string;
    defaultTertiary: string;
    defaultDisabled: string;
    defaultInverse: string;
    brand: string;
    brandInverse: string;
    brandHover: string;
    brandAccent: string;
    brandAccentInverse: string;
    stateWarning: string;
    stateWarningInverse: string;
    stateError: string;
    stateErrorInverse: string;
    stateSuccess: string;
    stateSuccessInverse: string;
    miscMagenta: string;
    miscMagentaInverse: string;
    miscTeal: string;
    miscTealInverse: string;
    miscPurple: string;
    miscPurpleInverse: string;
    miscCrimson: string;
    miscCrimsonInverse: string;
    miscGold: string;
    miscGoldInverse: string;
};
export declare const border: {
    defaultPrimary: string;
    defaultSecondary: string;
    defaultBrand: string;
    defaultAccent: string;
    defaultDisabled: string;
    defaultWhite: string;
    defaultInverse: string;
    stateError: string;
    stateWarning: string;
    stateSuccess: string;
    miscMagenta: string;
    miscTeal: string;
    miscPurple: string;
    miscCrimson: string;
    miscGold: string;
};
export declare const icon: {
    defaultPrimary: string;
    defaultSecondary: string;
    defaultTertiary: string;
    defaultDisabled: string;
    defaultInverse: string;
    brand: string;
    brandInverse: string;
    brandHover: string;
    accent: string;
    accentInverse: string;
    warning: string;
    warningInverse: string;
    error: string;
    errorInverse: string;
    success: string;
    successInverse: string;
    magenta: string;
    magentaInverse: string;
    teal: string;
    tealInverse: string;
    purple: string;
    purpleInverse: string;
    crimson: string;
    crimsonInverse: string;
    miscGold: string;
    miscGoldInverse: string;
};
declare const BaseColors: {
    bgFill: {
        defaultPrimary: string;
        /**
         * @deprecated May remove later
         */
        defaultPrimaryII: string;
        defaultSecondary: string;
        defaultTertiary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        brandSecondary: string;
        brandTertiary: string;
        brandHover: string;
        brandSecondaryHover: string;
        accent: string;
        accentSecondary: string;
        /**
         * @deprecated May remove later
         */
        accentSecondaryII: string;
        accentTertiary: string;
        accentHover: string;
        accentSecondaryHover: string;
        stateError: string;
        stateErrorSecondary: string;
        stateErrorHover: string;
        stateErrorSecondaryHover: string;
        stateWarning: string;
        stateWarningSecondary: string;
        stateSuccess: string;
        stateSuccessSecondary: string;
        miscMagenta: string;
        miscMagentaSecondary: string;
        miscTeal: string;
        miscTealSecondary: string;
        miscPurple: string;
        miscPurpleSecondary: string;
        miscCrimson: string;
        miscCrimsonSecondary: string;
        translucentPrimary: string;
        translucentSecondary: string;
        translucentTertiary: string;
        miscGold: string;
        miscGoldSecondary: string;
        miscGoldTertiary: string;
        miscGoldHover: string;
        miscGoldSecondaryHover: string;
    };
    icon: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultTertiary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        brandInverse: string;
        brandHover: string;
        accent: string;
        accentInverse: string;
        warning: string;
        warningInverse: string;
        error: string;
        errorInverse: string;
        success: string;
        successInverse: string;
        magenta: string;
        magentaInverse: string;
        teal: string;
        tealInverse: string;
        purple: string;
        purpleInverse: string;
        crimson: string;
        crimsonInverse: string;
        miscGold: string;
        miscGoldInverse: string;
    };
    border: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultBrand: string;
        defaultAccent: string;
        defaultDisabled: string;
        defaultWhite: string;
        defaultInverse: string;
        stateError: string;
        stateWarning: string;
        stateSuccess: string;
        miscMagenta: string;
        miscTeal: string;
        miscPurple: string;
        miscCrimson: string;
        miscGold: string;
    };
    text: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultTertiary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        brandInverse: string;
        brandHover: string;
        brandAccent: string;
        brandAccentInverse: string;
        stateWarning: string;
        stateWarningInverse: string;
        stateError: string;
        stateErrorInverse: string;
        stateSuccess: string;
        stateSuccessInverse: string;
        miscMagenta: string;
        miscMagentaInverse: string;
        miscTeal: string;
        miscTealInverse: string;
        miscPurple: string;
        miscPurpleInverse: string;
        miscCrimson: string;
        miscCrimsonInverse: string;
        miscGold: string;
        miscGoldInverse: string;
    };
    bgSurface: {
        defaultPrimary: string;
        defaultSecondary: string;
        defaultDisabled: string;
        defaultInverse: string;
        brand: string;
        accent: string;
        stateError: string;
        stateWarning: string;
        stateSuccess: string;
        miscMagenta: string;
        miscTeal: string;
        miscPurple: string;
        miscCrimson: string;
        overlayPrimary: string;
        miscGold: string;
    };
};
export default BaseColors;
//# sourceMappingURL=index.d.ts.map